export const TestConstant = {
    TEST_FIND_ONE: 'TEST_FIND_ONE',
    TEST_FIND_ONE_CLEAR: 'TEST_FIND_ONE_CLEAR',
    TEST_FIND_ALL: 'TEST_FIND_ALL',
    TEST_FIND_ALL_CLEAR: 'TEST_FIND_ALL_CLEAR',
    TEST_LOADING: 'TEST_LOADING',
    TEST_LOADING_FINISHED: 'TEST_LOADING_FINISHED',
    TEST_FIND_AVERAGE: 'TEST_FIND_AVERAGE',
    TEST_CLEAR_AVERAGE: 'TEST_CLEAR_AVERAGE',
    TEST_NOTIFICATION: 'TEST_NOTIFICATION'
}